name: App - Deploy

on:
  push:
    branches: [main]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    services:
      database-test:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: "docker"
          MYSQL_DATABASE: laravel
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v2

      - name: Verify laravel DB exists
        run: mysql --host 127.0.0.1 --port 3306 -uroot -pdocker -e "SHOW DATABASES LIKE 'laravel'"

      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.0"

      - name: Setup Project
        run: |
          composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
          chmod -R 777 storage bootstrap/cache

      - name: Execute tests via PHPUnit
        env:
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
        run: |
          php artisan test --without-tty

  build-and-push-docker-image:
    needs: run-tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Make .env
        env:
          SECRET_ENV: ${{ secrets.APP_ENV_PROD }}
        run: touch .env && echo "$SECRET_ENV" > .env

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./.docker/production/app.Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/laravel-cicd-docker:latest
